version: '3.1'

services:

  database:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ingrediant
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    ports:
      - "3309:3306"
    restart: always

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8082:8080

volumes:
  database:
    driver: local